server:
  tomcat:
    accesslog:
      enabled: true
      directory: ${FIRSTMEET_MSERVICE_DATA_BASEDIR:.}/logs/${HOSTNAME:1}/access-log
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://10.201.0.8:3306/user_center?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xqKKZ5xS%m!V^2pc
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  jpa:
    database: mysql
    show-sql: false
  #邮件
  mail:
    host: smtp.16801.com
    port: 25
    username: thai-support@16801.com
    password: 3a3d7d00gDN0Hdvj
    default-encoding: utf-8
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
facebook:
  access-token:
    verify-url: https://graph.facebook.com/debug_token
    get-token-url: https://graph.facebook.com/oauth/accessToken
google:
  user-login:
    enable-verify: false
chujian:
  main-account: email
  send-email:
    forget-password:
      theme: กู้คืนรหัสFirstmeet
      expire-time: 30
      base-path: https://ups.firstmeetgame.com/usercenter
  password:
    enable-encode: true
  visitor:
    enable: true
    username-prefix:
  channel-user-login:
    enable-verify: false
  token:
    key:
      jks-filepath: chujian.jks
      password: password
      alias: chujian
      public-key-string: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlTulF2dCQQiU4jkQMQHth084/OZcLFGkse6BQ0J5u47TOJ7PGPMAX1iqCrCwgbseDNLjMMpxLuX4ULbpjFrD/FN1uKmXEVwdP9zYCv22hE618XU6j3u0OEfsgZrupv9+lALxGZKyDfDRsjEy5KCXekAOiXDxJEUl/pNYla8MoJ5D9zjjUzUVq8i3pdL42sP9z6LKhtQXtzOiQ22zGST3mMzButpYXK55LHlgqYXb9hjBbcVIsZYP07Q4mt+NlT+x4crYp4Hirjl9rbUmQm7ZoL3GR8ErJnipPqOo7uKCAmwjKnBoRSu5836gG6kLOiSHtCdu8hp96G8sS95oWorflwIDAQAB
